controller_list:
  - name: fake_right_arm_controller
    joints:
      - right_arm_shoulder_pan_joint
      - right_arm_shoulder_lift_joint
      - right_arm_shoulder_roll_joint
      - right_arm_elbow_flex_joint
      - right_arm_forearm_flex_joint
      - right_arm_wrist_flex_joint
  - name: fake_right_gripper_controller
    joints:
      - right_gripper_finger_joint
  - name: fake_head_controller
    joints:
      - head_pan_joint
      - head_tilt_joint