<?xml version="1.0"?>

<robot name="pedestal_pi_no_gripper" xmlns:xacro="http://ros.org/wiki/xacro">

  <property name="BASE_MESH_SCALE" value="1.0"/>
  <property name="BASE_MESH_COLLISION_SCALE" value="0.0254"/>

  <property name="MESH_SCALE" value="0.001"/>
  <property name="MESH_COLLISION_SCALE" value="0.00105"/>
  <property name="GROUND_CLEARANCE" value="0.004" />
  <property name="LOWER_BASE_HEIGHT" value="0.26" />
  <property name="LOWER_BASE_RADIUS" value="0.075" />

  <material name="Green">
    <color rgba="0.0 0.8 0.0 1.0"/>
  </material>
  
  <material name="OffWhite">
    <color rgba="0.8 0.8 0.8 0.9"/>
  </material>

  <material name="White">
    <color rgba="1.0 1.0 1.0 1.0"/>
  </material>

  <material name="DarkGray">
     <color rgba="0.3 0.3 0.3 1.0"/>
  </material>
  
  <material name="LightGray">
     <color rgba="0.6 0.6 0.6 1.0"/>
  </material>
  
  <material name="Red">
     <color rgba="1.0 0.0 0.0 0.5"/>
  </material>
  
  <xacro:include filename="$(find rbx2_description)/urdf/pedestal_pi/pedestal_pi_pan_tilt_head.urdf.xacro" />

  <link name="base_link">
    <visual>
      <origin xyz="0 0 ${GROUND_CLEARANCE}" rpy="0 0 1.57" />
      <geometry>
          <mesh filename="package://rbx2_description/meshes/pedestal_pi/pedestal_pi.dae" scale="${BASE_MESH_SCALE} ${BASE_MESH_SCALE} ${BASE_MESH_SCALE}"/>
      </geometry>
    </visual>

    <collision>
      <origin xyz="0 0 ${GROUND_CLEARANCE}" rpy="0 0 1.57" />
       <geometry>
          <mesh filename="package://rbx2_description/meshes/pedestal_pi/pedestal_pi_collision.dae" scale="${BASE_MESH_COLLISION_SCALE} ${BASE_MESH_COLLISION_SCALE} ${BASE_MESH_COLLISION_SCALE}"/>
       </geometry>
     </collision>

   </link>
   
   <!-- Add a foot_print link and joint -->
   <link name="base_footprint">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
         <box size="0.01 0.01 0.0001" />
      </geometry>
    </visual>
   </link>
   
   <joint name="base_to_footprint" type="fixed">
     <origin xyz="0 0 0" rpy="0 0 0" />        
     <parent link="base_link"/>
     <child link="base_footprint" />
   </joint>
    
   <!-- Attach the head -->
   <head name="head_base" parent="base" color="White">
     <origin xyz="-${AX12_DEPTH/4} 0 ${0.438 + GROUND_CLEARANCE}" rpy="${PI/2} 0 ${PI/2}" />
   </head>
   
</robot>
