joint_limits:
  right_arm_wrist_flex_joint:
    has_velocity_limits: true
    max_velocity: 1.571
    has_acceleration_limits: false
    max_acceleration: 0
  right_arm_shoulder_pan_joint:
    has_velocity_limits: true
    max_velocity: 1.571
    has_acceleration_limits: false
    max_acceleration: 0
  right_arm_forearm_flex_joint:
    has_velocity_limits: true
    max_velocity: 1.571
    has_acceleration_limits: false
    max_acceleration: 0
  head_pan_joint:
    has_velocity_limits: true
    max_velocity: 1.571
    has_acceleration_limits: false
    max_acceleration: 0
  right_arm_shoulder_roll_joint:
    has_velocity_limits: true
    max_velocity: 1.571
    has_acceleration_limits: false
    max_acceleration: 0
  head_tilt_joint:
    has_velocity_limits: true
    max_velocity: 1.571
    has_acceleration_limits: false
    max_acceleration: 0
  right_arm_elbow_flex_joint:
    has_velocity_limits: true
    max_velocity: 1.571
    has_acceleration_limits: false
    max_acceleration: 0
  right_arm_shoulder_lift_joint:
    has_velocity_limits: true
    max_velocity: 1.571
    has_acceleration_limits: false
    max_acceleration: 0